name: cinecapp
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase (versions that are compatible with each other and cached_network_image)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4


  # State management
  provider: ^6.1.5

  # Image handling (downgraded for compatibility)
  image_picker: ^1.0.7
  cached_network_image: ^3.2.3
  flutter_staggered_animations: ^1.0.0
  carousel_slider: ^5.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png