// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbi5WXFrpKLTY2IKKurKrObn3ZuV_QNw4',
    appId: '1:495298121905:web:4cdf6e320f925f347d1290',
    messagingSenderId: '495298121905',
    projectId: 'cinecapp-6a3a7',
    authDomain: 'cinecapp-6a3a7.firebaseapp.com',
    storageBucket: 'cinecapp-6a3a7.firebasestorage.app',
    measurementId: 'G-W2HTFPXZS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ3v4660v1wXgNc89MmRQe4toFR7AXijE',
    appId: '1:495298121905:android:34f90e8e65bd6fdd7d1290',
    messagingSenderId: '495298121905',
    projectId: 'cinecapp-6a3a7',
    storageBucket: 'cinecapp-6a3a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkhCPZ6sYBI19BOW4HqbbyxkFmWxheYD0',
    appId: '1:495298121905:ios:a1dbd4127bd769687d1290',
    messagingSenderId: '495298121905',
    projectId: 'cinecapp-6a3a7',
    storageBucket: 'cinecapp-6a3a7.firebasestorage.app',
    iosBundleId: 'com.example.cinecapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkhCPZ6sYBI19BOW4HqbbyxkFmWxheYD0',
    appId: '1:495298121905:ios:a1dbd4127bd769687d1290',
    messagingSenderId: '495298121905',
    projectId: 'cinecapp-6a3a7',
    storageBucket: 'cinecapp-6a3a7.firebasestorage.app',
    iosBundleId: 'com.example.cinecapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbi5WXFrpKLTY2IKKurKrObn3ZuV_QNw4',
    appId: '1:495298121905:web:b59951a392ae197c7d1290',
    messagingSenderId: '495298121905',
    projectId: 'cinecapp-6a3a7',
    authDomain: 'cinecapp-6a3a7.firebaseapp.com',
    storageBucket: 'cinecapp-6a3a7.firebasestorage.app',
    measurementId: 'G-V5TH6WQ54Z',
  );
}
